version: '3.8'

services:
  # 개발 환경용 Next.js 애플리케이션
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: kkutu-gosu-app-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    networks:
      - kkutu-network
    volumes:
      # 소스 코드 마운트 (핫 리로드를 위해)
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped

networks:
  kkutu-network:
    driver: bridge
