version: '3.8'

services:
  # Next.js 애플리케이션
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kkutu-gosu-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - kkutu-network
    restart: unless-stopped
    volumes:
      # 로그나 임시 파일을 위한 볼륨 (선택사항)
      - app-data:/app/data

volumes:
  app-data:
    driver: local

networks:
  kkutu-network:
    driver: bridge
