version: '3.8'

services:
  # 개발 환경용 Next.js 애플리케이션
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: kkutu-gosu-app-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    networks:
      - kkutu-network
    volumes:
      # 소스 코드 마운트 (핫 리로드를 위해)
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped

  # Redis 서비스
  redis:
    image: redis:7-alpine
    container_name: kkutu-gosu-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis-dev-data:/data
    networks:
      - kkutu-network
    restart: unless-stopped
    command: redis-server --appendonly yes

  # Redis Commander (개발용 관리 도구)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: kkutu-gosu-redis-commander-dev
    hostname: redis-commander
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
    networks:
      - kkutu-network

volumes:
  redis-dev-data:
    driver: local

networks:
  kkutu-network:
    driver: bridge
